version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8091:8080"
      - "50000:50000"
    volumes:
      - "$HOME/mount/jenkins/jenkins_home:/var/jenkins_home"
      - "$HOME/.m2:/root/.m2"
      - "$HOME/.ssh:/root/.ssh"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/bin/docker:/usr/bin/docker"
      - "/etc/docker/daemon.json:/etc/docker/daemon.json"
      - "/etc/localtime:/etc/localtime"
    user: root
    restart: always

